# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'added.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_erradd(object):
    def setupUi(self, erradd):
        erradd.setObjectName("erradd")
        erradd.resize(540, 458)
        erradd.setMinimumSize(QtCore.QSize(540, 458))
        erradd.setMaximumSize(QtCore.QSize(540, 458))
        self.centralwidget = QtWidgets.QWidget(erradd)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(246, 23))
        self.label.setMaximumSize(QtCore.QSize(246, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.inuse = QtWidgets.QListWidget(self.centralwidget)
        self.inuse.setObjectName("inuse")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.inuse)
        self.added = QtWidgets.QListWidget(self.centralwidget)
        self.added.setMinimumSize(QtCore.QSize(270, 382))
        self.added.setMaximumSize(QtCore.QSize(270, 382))
        self.added.setObjectName("added")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.added)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(522, 23))
        self.pushButton.setMaximumSize(QtCore.QSize(522, 23))
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.pushButton)
        erradd.setCentralWidget(self.centralwidget)

        self.retranslateUi(erradd)
        QtCore.QMetaObject.connectSlotsByName(erradd)

    def retranslateUi(self, erradd):
        _translate = QtCore.QCoreApplication.translate
        erradd.setWindowTitle(_translate("err4", "MainWindow"))
        self.label.setText(_translate("err4", "Добавленные слова:"))
        self.label_2.setText(_translate("err4", "Эти слова уже есть в словаре:"))
        self.pushButton.setText(_translate("err4", "Отлично"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    erradd = QtWidgets.QMainWindow()
    ui = Ui_erradd()
    ui.setupUi(erradd)
    erradd.show()
    sys.exit(app.exec_())
