# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addword.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addword(object):
    def setupUi(self, addword):
        addword.setObjectName("addword")
        addword.resize(602, 338)
        addword.setMinimumSize(QtCore.QSize(602, 338))
        addword.setMaximumSize(QtCore.QSize(602, 338))
        self.centralwidget = QtWidgets.QWidget(addword)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add.setFont(font)
        self.add.setObjectName("add")
        self.gridLayout.addWidget(self.add, 3, 1, 1, 1)
        self.back = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.back.setFont(font)
        self.back.setObjectName("back")
        self.gridLayout.addWidget(self.back, 3, 2, 1, 1)
        self.all = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.all.setFont(font)
        self.all.setObjectName("all")
        self.gridLayout.addWidget(self.all, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.slova = QtWidgets.QListWidget(self.centralwidget)
        self.slova.setObjectName("slova")
        self.gridLayout.addWidget(self.slova, 1, 0, 1, 3)
        addword.setCentralWidget(self.centralwidget)

        self.retranslateUi(addword)
        QtCore.QMetaObject.connectSlotsByName(addword)

    def retranslateUi(self, addword):
        _translate = QtCore.QCoreApplication.translate
        addword.setWindowTitle(_translate("addword", "MainWindow"))
        self.add.setText(_translate("addword", "Добавить "))
        self.back.setText(_translate("addword", "Назад"))
        self.all.setText(_translate("addword", "Добавить все"))
        self.label.setText(_translate("addword", "Какое из слов вы хотите добавить в словарь?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addword = QtWidgets.QMainWindow()
    ui = Ui_addword()
    ui.setupUi(addword)
    addword.show()
    sys.exit(app.exec_())
