# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Start(object):
    def setupUi(self, start):
        start.setObjectName("start")
        start.resize(634, 336)
        font = QtGui.QFont()
        font.setPointSize(12)
        start.setFont(font)
        self.centralwidget = QtWidgets.QWidget(start)
        self.centralwidget.setObjectName("centralwidget")
        self.info = QtWidgets.QListWidget(self.centralwidget)
        self.info.setGeometry(QtCore.QRect(290, 10, 341, 271))
        self.info.setObjectName("info")
        self.word = QtWidgets.QTextEdit(self.centralwidget)
        self.word.setGeometry(QtCore.QRect(10, 10, 251, 31))
        self.word.setObjectName("word")
        self.trans = QtWidgets.QPushButton(self.centralwidget)
        self.trans.setGeometry(QtCore.QRect(10, 50, 111, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trans.sizePolicy().hasHeightForWidth())
        self.trans.setSizePolicy(sizePolicy)
        self.trans.setMinimumSize(QtCore.QSize(111, 31))
        self.trans.setMaximumSize(QtCore.QSize(111, 31))
        self.trans.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.trans.setObjectName("trans")
        self.say = QtWidgets.QPushButton(self.centralwidget)
        self.say.setGeometry(QtCore.QRect(150, 50, 111, 31))
        self.say.setObjectName("say")
        self.open = QtWidgets.QPushButton(self.centralwidget)
        self.open.setGeometry(QtCore.QRect(0, 300, 141, 31))
        self.open.setObjectName("open")
        self.addd = QtWidgets.QPushButton(self.centralwidget)
        self.addd.setGeometry(QtCore.QRect(290, 300, 341, 31))
        self.addd.setObjectName("add")
        start.setCentralWidget(self.centralwidget)

        self.retranslateUi(start)
        QtCore.QMetaObject.connectSlotsByName(start)

    def retranslateUi(self, start):
        _translate = QtCore.QCoreApplication.translate
        start.setWindowTitle(_translate("start", "MainWindow"))
        self.trans.setText(_translate("start", "Перевод"))
        self.say.setText(_translate("start", "Произнести"))
        self.open.setText(_translate("start", "Открыть словарь"))
        self.addd.setText(_translate("start", "Добавить в словарь"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    start = QtWidgets.QMainWindow()
    ui = Ui_Start()
    ui.setupUi(start)
    start.show()
    sys.exit(app.exec_())
