# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wordbook2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fw = QtWidgets.QTextEdit(self.centralwidget)
        self.fw.setGeometry(QtCore.QRect(90, 10, 261, 31))
        self.fw.setObjectName("fw")
        self.words = QtWidgets.QListWidget(self.centralwidget)
        self.words.setGeometry(QtCore.QRect(20, 60, 331, 491))
        self.words.setObjectName("listWidget_2")
        self.trans = QtWidgets.QListWidget(self.centralwidget)
        self.trans.setGeometry(QtCore.QRect(370, 10, 411, 541))
        self.trans.setObjectName("trans")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(690, 560, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.back.setFont(font)
        self.back.setObjectName("back")
        self.found = QtWidgets.QPushButton(self.centralwidget)
        self.found.setGeometry(QtCore.QRect(10, 10, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.found.setFont(font)
        self.found.setObjectName("found")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.back.setText(_translate("MainWindow", "Назад"))
        self.found.setText(_translate("MainWindow", "Найти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
